Repository web3ui/web3uikit, pull requests merged in 2022-09, with the labels that each got.

#790 [Fix]: Select styles and Add height customizations
  .changeset/sour-beans-reflect.md
  packages/core/src/lib/Select/Select.stories.tsx
  packages/core/src/lib/Select/SelectBeta/SelectBeta.styles.ts
  packages/core/src/lib/Select/SelectBeta/SelectBeta.tsx
  packages/core/src/lib/Select/SelectBeta/components/SelectMenuList.tsx
  packages/core/src/lib/Select/SelectBeta/components/SelectedItemsList.tsx
  packages/core/src/lib/Select/types.ts
Labels: bug, in-review

#804 fix(Stepper): complete title is H2
  .changeset/neat-brooms-play.md
  packages/core/src/lib/Stepper/Stepper.tsx
Labels: bug

#789 [Feat]: New Credit card designs
  .changeset/hot-tools-jam.md
  packages/core/src/lib/CreditCard/CreditCard.stories.tsx
  packages/core/src/lib/CreditCard/CreditCard.tsx
  packages/core/src/lib/CreditCard/LargeCreditCard/LargeCreditCard.styles.ts
  packages/core/src/lib/CreditCard/LargeCreditCard/index.tsx
  packages/core/src/lib/CreditCard/SmallCreditCard/SmallCreditCard.styles.ts
  packages/core/src/lib/CreditCard/SmallCreditCard/index.tsx
  packages/core/src/lib/CreditCard/types.ts
  packages/core/src/lib/Radios/Radios.cc.stories.tsx
  packages/core/src/lib/Radios/Radios.styles.ts
  packages/core/src/lib/Radios/Radios.tsx
  packages/icons/src/lib/icons/CreditCard2.tsx
  packages/icons/src/lib/icons/index.ts
  packages/icons/src/lib/svgs/credit-card2.svg
Labels: feature
