Repository web3ui/web3uikit, pull requests merged in 2022-07, with the labels that each got.

#692 docs:correct installation of yarn in contribute.md
  CONTRIBUTE.md
Labels: documentation

#687 fix(Checkbox): box alignment and hidden input for validation prompt
  src/components/Checkbox/Checkbox.styles.ts
  src/components/Upload/Upload.test.tsx
  src/components/Upload/Upload.tsx
  src/components/Upload/types.ts
Labels: bug, in-review

#697 Add new icons and solana icon fix
  src/components/Icon/collection.tsx
  src/components/Icon/icons/cart-bag.tsx
  src/components/Icon/icons/key-icon.tsx
  src/components/Icon/icons/lock-reset.tsx
  src/components/Icon/icons/phone.tsx
  src/components/Icon/icons/roadmap.tsx
  src/components/Icon/icons/solana.tsx
Labels: in-review

#689 Feat ens avatar addedcomp
  src/components/ENSAvatar/ENSAvatar.stories.tsx
  src/components/ENSAvatar/ENSAvatar.styles.ts
  src/components/ENSAvatar/ENSAvatar.tsx
  src/components/ENSAvatar/index.tsx
  src/components/ENSAvatar/types.ts
  src/index.ts
Labels: in-review

#699 feat:added ens support in connect button
  src/components/ConnectButton/ConnectButton.tsx
Labels: feature, blocked, web3

#702 Dependencies update
  .storybook/main.js
  package.json
  yarn.lock
Labels: in-review

#696 Feat:blocknumber addedcomp
  src/components/BlockNumber/BlockNumber.stories.tsx
  src/components/BlockNumber/BlockNumber.tsx
  src/components/BlockNumber/index.tsx
  src/components/ConnectButton/ConnectButton.tsx
  src/index.ts
Labels: in-review

#718 Popover Dropdown inside Dropdown
  src/components/PopoverDropdown/PopoverDropdown.stories.tsx
  src/components/PopoverDropdown/PopoverDropdown.styles.tsx
Labels: feature, in-review

#720 fix(Popover Element): text overflow issue
  .prettierrc
  src/components/PopoverDropdown/PopoverDropdown.stories.tsx
  src/components/PopoverElement/PopoverElement.styles.tsx
Labels: in-review

#710 Fix: Tablist auto width and overflow
  src/components/Tabs/Tabs.stories.tsx
  src/components/Tabs/Tabs.styles.ts
  src/components/Tabs/Tabs.test.tsx
  src/components/Tabs/TabsList.tsx
  src/components/Tabs/types.ts
Labels: feature, in-review

#721 fix(NFT): Add contract type prop and manipulate video link
  src/components/NFT/NFT.fetched.tsx
  src/components/NFT/NFT.tsx
  src/components/NFT/NFT.utils.tsx
  src/components/NFT/types.ts
Labels: in-review

#748 fix(CryptoLogo Illustration): minor alignments
  packages/core/src/lib/CryptoLogos/bgConfig.ts
  packages/core/src/lib/Illustrations/Illustration.stories.tsx
  packages/core/src/lib/Illustrations/types.ts
Labels: feature
