Repository web3ui/web3uikit, pull requests merged in 2022-03, with the labels that each got.

#324 feat(Input): dynamic value and filled hack story
  src/components/Input/Input.stories.tsx
  src/components/Input/Input.test.tsx
  src/components/Input/Input.tsx
Labels: feature, in-review

#329 completed the refactor of hero component
  src/components/Hero/Hero.stories.tsx
  src/components/Hero/Hero.styles.ts
  src/components/Hero/Hero.tsx
  src/components/Hero/types.ts
Labels: feature

#327 fix(Input): removing bad value fix
  src/components/Input/Input.tsx
Labels: bug

#342 fix(NFTCollection): minor fix for more responsive images
  src/components/NFTCollection/NFTCard.tsx
  src/components/NFTCollection/NFTCollection.styles.ts
  src/components/NFTCollection/NFTCollection.tsx
Labels: feature
