Repository web3ui/web3uikit, pull requests merged in 2022-04, with the labels that each got.

#356 355 react refactor accordion
  README.md
  src/components/Accordion/Accordion.stories.tsx
  src/components/Accordion/Accordion.styles.ts
  src/components/Accordion/Accordion.test.tsx
  src/components/Accordion/Accordion.tsx
Labels: bug

#394 add signingMessage to ConnectButton
  src/components/ConnectButton/ConnectButton.tsx
  src/components/ConnectButton/connectors.ts
  src/components/ConnectButton/types.ts
  src/components/WalletModal/WalletModal.tsx
  src/components/WalletModal/config.ts
  src/decorators.tsx
Labels: feature

#420 feat: fix todo
  src/components/Todo/Todo.tsx
Labels: bug

#410 Draft: NFT Balance + NFT Card
  package.json
  src/components/NFT/NFT.fetched.tsx
  src/components/NFT/NFT.modal.tsx
  src/components/NFT/NFT.stories.tsx
  src/components/NFT/NFT.styles.tsx
  src/components/NFT/NFT.tsx
  src/components/NFT/NFT.utils.tsx
  src/components/NFT/index.tsx
  src/components/NFT/types.ts
  src/components/NFTBalance/NFTBalance.stories.tsx
  src/components/NFTBalance/NFTBalance.styles.ts
  src/components/NFTBalance/NFTBalance.tsx
  src/components/NFTBalance/index.tsx
  src/components/NFTBalance/types.ts
  src/components/NFTCollection/NFTCard.tsx
  src/components/NFTCollection/NFTCollection.stories.tsx
  src/components/NFTCollection/NFTCollection.styles.ts
  src/components/NFTCollection/NFTCollection.test.tsx
  src/components/NFTCollection/NFTCollection.tsx
  src/components/NFTCollection/index.tsx
  src/components/NFTCollection/types.ts
  src/index.ts
  yarn.lock
Labels: in-progress

#344 feat(React18): upgrade
  README.md
  package.json
  src/components/Form/Form.tsx
  src/components/Modal/Modal.tsx
  src/components/NewComp/NewComp.tsx
  yarn.lock
Labels: blocked

#485 484 form after submit
  src/components/Form/Form.tsx
  src/components/Stepper/Stepper.test.tsx
Labels: bug

#526 Revert "Revert "fix(fonts): import statements removed, web safe fonts…
  src/components/Card/Card.stories.tsx
  src/components/CryptoCards/CryptoCards.styles.tsx
  src/components/Typography/Typography.styles.ts
  src/components/Typography/Typography.tsx
  src/components/Widget/Widget.styles.tsx
  src/styles/fonts.ts
Labels: bug
