Repository web3ui/web3uikit, pull requests merged in 2022-05, with the labels that each got.

#539 [feat]: Verify code component
  src/components/VerifyCode/VerifyCode.stories.tsx
  src/components/VerifyCode/VerifyCode.styles.ts
  src/components/VerifyCode/VerifyCode.test.tsx
  src/components/VerifyCode/VerifyCode.tsx
  src/components/VerifyCode/index.tsx
  src/components/VerifyCode/types.ts
  src/index.ts
Labels: feature

#552 546 input onblur ref props
  src/components/Checkbox/Checkbox.stories.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/types.ts
  src/components/Input/Input.stories.tsx
  src/components/Input/Input.test.tsx
  src/components/Input/Input.tsx
  src/components/Input/types.ts
  src/components/Radios/Radios.cc.stories.tsx
  src/components/Radios/Radios.stories.tsx
  src/components/Radios/Radios.tsx
  src/components/Radios/types.tsx
  src/components/Select/Select.tsx
  src/components/Select/types.ts
  src/components/TextArea/TextArea.stories.tsx
  src/components/TextArea/TextArea.tsx
  src/components/TextArea/types.tsx
Labels: in-review

#563 449: onTab feature added to the different button themes
  src/components/Button/styles/coloredThemes.ts
  src/components/Button/styles/standardThemes.ts
Labels: in-review

#575 hero font size for smaller devices
  src/components/Hero/Hero.styles.ts
Labels: in-review

#564 feat/wp5-cra-polyfill
  package.json
Labels: bug

#588 Commented out table logging
  src/components/Button/Button.styles.ts
Labels: bug

#613 fix(Logo): new logos, make it bigger
  src/components/Logo/Logo.stories.tsx
  src/components/Logo/Logo.test.tsx
  src/components/Logo/Logo.tsx
  src/components/Logo/images/moralisLogoDefault.tsx
  src/components/Logo/images/moralisLogoIcon.tsx
  src/components/Logo/types.ts
  yarn.lock
Labels: feature

#624 [fix]:... content appear only when you hover over child element
  src/components/Tooltip/Tooltip.styles.ts
  src/components/Tooltip/Tooltip.test.tsx
  src/components/Tooltip/Tooltip.tsx
Labels: in-review
